gfyage/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gfyage_app.urls', namespace='gfyg')),
]

gfyage_app/urls.py
from django.conf.urls import url, static, include
from . import views
from django.conf import settings

urlpatterns = [
    # 主页
    url(r'^$', views.index, name='index'),
    url(r'^yageyinpin/$',views.audios, name='audios'),
    url(r'^yageyinpin/(?P<audio_id>\d+)/$', views.audio, name='audio'),  # 雅歌音频内容

    url(r'^yanchangshipin/$', views.video, name='video'),
    url(r'^xueshuzhuanti/$', views.academic, name='academic'),
    url(r'^fangtanshilu/$', views.interview, name='interview'),
    url(r'^shigewenzhai/$', views.poem, name='poem'),
    url(r'^shifanjiaocai/$', views.normal, name='normal'),
    url(r'^guofengsecai/$', views.folk, name='folk'),
    url(r'mdeditor/', include('mdeditor.urls')),
]

app_name = 'gfyg'

# if settings.DEBUG:
#     # static files (images, css, javascript, etc.)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gfyage_app/models.py
from django.db import models

# Create your models here.
from mdeditor.fields import MDTextField


class Audio(models.Model):
    id = models.AutoField(primary_key=True)
    Title = models.CharField('标题', max_length=20)  # 标题
    Date = models.DateField('时间')   # 发表日期
    Creator = models.CharField('原创', max_length=20)  # 原创
    SongName = models.CharField('歌曲名', max_length=10)  # 歌曲名
    Lyricist = models.CharField('作词者', max_length=10, blank=True)  # 作词者
    Compose = models.CharField('作曲者', max_length=10, blank=True)  # 作曲者
    Singer = models.CharField('演唱者', max_length=10)  # 演唱者
    Type = models.CharField('歌曲类型', max_length=10)  # 歌曲类型
    CopyRight = models.CharField('版权所属', max_length=20)  # 版权所属
    Location = models.CharField('演唱地点', max_length=10)  # 演唱地点
    SingDate = models.CharField('演唱时间', max_length=20)  # 演唱时间
    Accompany = models.CharField('伴奏', max_length=20)  # 伴奏
    CoverImage = models.ImageField(upload_to='audio', verbose_name='图片', null=True)  # 封面图片
    Lyrics = models.TextField('歌词')  # 歌词
    SingerIntro = MDTextField('演唱者介绍')  # 演唱者介绍
    SongIntro = MDTextField('歌曲介绍')  # 歌曲介绍
    Tag = models.CharField('标签', max_length=20)  # 页面最后的一个标签
    MusciPath = models.FileField('上传音频', blank=True, upload_to='audio')

    class Meta:
        verbose_name = '音频'
        verbose_name_plural = verbose_name

gfyage_app/views.py
from django.shortcuts import render, get_object_or_404
from .models import Audio
import markdown


def index(request):
    # 国风雅歌主页
    return render(request, 'gfyage_app/index.html')


def audios(request):
    # 雅歌音频
    audios = Audio.objects.filter().order_by('id')[0]
    context = {'audio': audios}
    return render(request, 'gfyage_app/audios.html', context)


def audio(request, audio_id):
    # 音频详细界面
    audio = Audio.objects.get(id=audio_id)
    audio.SingerIntro = markdown.markdown(audio.SingerIntro, extensions=['markdown.extensions.extra',  # 用于标题、表格、引用这些基本转换
                                                           'markdown.extensions.codehilite',  # 用于语法高亮
                                                           'markdown.extensions.toc',])[3:-4:1]  # 用于生成目录
    audio.SongIntro = markdown.markdown(audio.SongIntro,
                                          extensions=['markdown.extensions.extra',  # 用于标题、表格、引用这些基本转换
                                                      'markdown.extensions.codehilite',  # 用于语法高亮
                                                      'markdown.extensions.toc', ])  # 用于生成目录
    context = {'audio': audio}
    return render(request, 'gfyage_app/audio.html', context)


def video(request):
    # 演唱视频
    return render(request, 'gfyage_app/video.html')


def academic(request):
    # 学术专题
    return render(request, 'gfyage_app/academic.html')


def interview(request):
    # 访谈实录
    return render(request, 'gfyage_app/interview.html')


def poem(request):
    # 诗歌文摘
    return render(request, 'gfyage_app/poem.html')


def normal(request):
    # 师范教材
    return render(request, 'gfyage_app/normal.html')


def folk(request):
    # 国风色彩
    return render(request, 'gfyage_app/folk.html')

templates/base.html
{% load bootstrap3 %}
{% load static %}
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-widthm, initial-scale=1">
    <title>国风雅歌</title>
    <link href="{% static 'images/favicon.ico' %}" rel="shortcut icon">
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>

<body>
<nav class="navbar navbar-default">
</nav>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container-fluid">
    <div class="navbar-header">
        <a class="navbar-brand" href="{% url 'gfyg:index' %}">首页</a>
    </div>
    <div>
        <ul class="nav navbar-nav">
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    雅歌音频 <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="{% url 'gfyg:audios' %}">全部</a></li>
                    <li><a href="#">国风雅歌</a></li>
                    <li><a href="#">有声诗歌</a></li>
                    <li><a href="#">名族歌曲</a></li>
                    <li><a href="#">歌曲翻译</a></li>
                </ul>
            </li>

            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    演唱视频 <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="{% url 'gfyg:video' %}">演唱视频</a></li>
                </ul>
            </li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    学术专题 <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="{% url 'gfyg:academic' %}">学术专题</a></li>
                </ul>
            </li>

            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    访谈实录 <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="{% url 'gfyg:interview' %}">访谈实录</a></li>
                </ul>
            </li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    诗歌文摘 <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="{% url 'gfyg:poem' %}">全部</a></li>
                    <li><a href="#">国风雅歌</a></li>
                    <li><a href="#">经典诗歌</a></li>
                    <li><a href="#">民间色彩</a></li>
                    <li class="divider"></li>
                    <li><a href="#">其他</a></li>
                </ul>
            </li>

            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    师范教材 <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="{% url 'gfyg:normal' %}">全部</a></li>
                    <li><a href="#">雅歌三百首</a></li>
                    <li><a href="#">精品著作</a></li>
                    <li><a href="#">作者访谈</a></li>
                    <li class="divider"></li>
                    <li><a href="#">媒体报道</a></li>
                </ul>
            </li>

            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    国风色彩 <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="{% url 'gfyg:folk' %}">江汉民歌</a></li>
                    <li><a href="#">江淮民歌</a></li>
                    <li><a href="#">赣民歌</a></li>
                    <li><a href="#">东北平原民歌</a></li>
                    <li><a href="#">西北高原民歌</a></li>
                    <li><a href="#">江浙民歌</a></li>
                    <li><a href="#">闽台民歌</a></li>
                    <li><a href="#">粤民歌</a></li>
                    <li><a href="#">湘民歌</a></li>
                    <li><a href="#">西南高原民歌</a></li>
                    <li><a href="#">客家民歌</a></li>
                </ul>
            </li>
        </ul>
    </div>
    </div>
</nav>


{% block content %}{% endblock content %}

templates/gfyage_app/academic.html
{% extends "base.html" %}

{% block content %}
<p>学术专题</p>

{% endblock content %}

templates/gfyage_app/folk.html
{% extends "base.html" %}

{% block content %}
<p>国风色彩</p>

{% endblock content %}

templates/gfyage_app/index.html
{% extends "base.html" %}

{% block content %}
<p>主页</p>

{% endblock content %}

templates/gfyage_app/interview.html
{% extends "base.html" %}

{% block content %}
<p>访谈实录</p>

{% endblock content %}

templates/gfyage_app/normal.html
{% extends "base.html" %}

{% block content %}
<p>师范教材</p>

{% endblock content %}

templates/gfyage_app/poem.html
{% extends "base.html" %}

{% block content %}
<p>诗歌文摘</p>

{% endblock content %}

templates/gfyage_app/video.html
{% extends "base.html" %}

{% block content %}
<p>演唱视频</p>

{% endblock content %}